# Generated by Django 4.0.4 on 2022-07-29 16:49

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('id_film', models.CharField(default='none', max_length=100)),
                ('img', models.ImageField(default='none', upload_to=films.models.get_image_path, verbose_name='Img')),
                ('yearProd', models.CharField(default='none', max_length=10)),
                ('country', models.CharField(default='none', max_length=40)),
                ('genre', models.CharField(default='none', max_length=200)),
                ('director', models.CharField(default='none', max_length=100)),
                ('script', models.CharField(default='none', max_length=300)),
                ('producer', models.CharField(default='none', max_length=200)),
                ('Operator', models.CharField(default='none', max_length=200)),
                ('Budget', models.CharField(default='none', max_length=40)),
                ('Fees', models.CharField(default='none', max_length=100)),
                ('premiere', models.CharField(default='none', max_length=40)),
                ('Age', models.CharField(default='none', max_length=40)),
                ('rating', models.CharField(default='none', max_length=40)),
                ('time', models.CharField(default='none', max_length=40)),
                ('description', models.TextField(default='none')),
            ],
        ),
    ]
