# Generated by Django 4.0.4 on 2022-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='angl_name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
