# Generated by Django 4.0.4 on 2022-07-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_angl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url_img',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
