# Generated by Django 4.0.4 on 2022-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_url_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ganer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='dateTime'),
        ),
        migrations.AddField(
            model_name='film',
            name='tg_age',
            field=models.ManyToManyField(to='films.age'),
        ),
        migrations.AddField(
            model_name='film',
            name='tg_country',
            field=models.ManyToManyField(to='films.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='tg_genre',
            field=models.ManyToManyField(to='films.ganer'),
        ),
        migrations.AddField(
            model_name='film',
            name='tg_year',
            field=models.ManyToManyField(to='films.year'),
        ),
    ]
