# Generated by Django 4.0.4 on 2022-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_age_country_ganer_year_film_datetime_film_tg_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tg_genre',
            field=models.ManyToManyField(default='none', to='films.ganer'),
        ),
    ]
