# Generated by Django 4.0.4 on 2022-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_tg_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='tg_type',
            field=models.ManyToManyField(to='films.type'),
        ),
    ]
