# Generated by Django 4.0.4 on 2022-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_type_film_tg_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persons', models.CharField(max_length=100)),
                ('name', models.CharField(default='none', max_length=200)),
                ('enName', models.CharField(default='none', max_length=200)),
                ('description', models.CharField(default='none', max_length=200)),
                ('enProfession', models.CharField(default='none', max_length=200)),
                ('photo', models.CharField(default='none', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='tg_persons',
            field=models.ManyToManyField(default='none', to='films.persons'),
        ),
    ]
