# Generated by Django 4.0.4 on 2022-08-05 16:52

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_persons_film_tg_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('img', models.ImageField(default='none', upload_to=films.models.get_image_path, verbose_name='Img')),
                ('description', models.TextField(default='none')),
                ('films', models.ManyToManyField(default='none', to='films.film')),
            ],
        ),
    ]
