# Generated by Django 4.1.1 on 2022-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
