# Generated by Django 4.1 on 2022-08-20 13:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='none', upload_to=main.models.get_image_path, verbose_name='Img')),
                ('name', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
